### ISSUE TITLE
Title does not link to the correct the page

### ISSUE THREAD

**Issue by anthonydresser** [ibmcnxdev/photosharing-nodejs#29]
The title on the navbar links to /# rather than /#/

**Comment by vfrancis** [comment]
Any reason we have to specifically say /#/ vs just #?

**Comment by anthonydresser** [comment]
I think it has to do with a limitation of the angular routing, anything with # is handled by angular.

**Comment by anthonydresser** [comment]
Currently then link is using "#", probably as a placeholder. I tried replacing it with "/#/" and it correctly redirects to the front page.

**Comment by vfrancis** [comment]
Ahh I see. Ok got it. Let's assign to Dan for now then.
