### ISSUE TITLE
401 should be handled by the front end to relogin the user

### ISSUE THREAD

**Issue by anthonydresser** [ibmcnxdev/photosharing-nodejs#31]

**Comment by vfrancis** [comment]
Do you mean 401? The 403 code is for authorization, so it shouldn't redirect to any login but rather say 'You're not authorized to access this'. If the front end hits an 401, then it should redirect to login.

**Comment by anthonydresser** [comment]
O ops, I should be returning 401 then. Currently I'm returning 403 if I can't find a session for the client. I'll change that to 401, but that should still be handled by the client, I thought about redirecting to login from the server, however because angular is handling the api requests, redirecting angular wouldn't actually do anything to the frontend.

**Comment by vfrancis** [comment]
Yup we should convert any "missing session" or lack of session to 401. All 403's should only come from the interaction with the Connections servers. Created a new item for you for that. Will rename this one to 401.
