### ISSUE TITLE
Feed should use thumbnails rather than full images

### ISSUE THREAD

**Issue by anthonydresser** [ibmcnxdev/photosharing-nodejs#36]
Should we use thumbnails for the feed rather than the full images? If so this will have to be changed in the front end.

**Comment by anthonydresser** [comment]
Please add as an enhancement if you think we should

**Comment by vfrancis** [comment]
Yeah we should switch to thumbnails.

**Comment by dlipeles** [comment]
Anthony and I set up the code for this, one thing to note, thumbnails are a bit pixelated we should decide if the (marginal) gain in performance is worth the reduced quality. Alternatively we can try to make the row elements smaller..

**Comment by vfrancis** [comment]
There are multiple thumbnail resolutions that you can leverage, are you using the biggest one, renditionKind=largeview ?

**Comment by anthonydresser** [comment]
i am passing this:  {  
                  "$":{  
                     "href":"https://apps.na.collabserv.com/files/oauth/api/library/56fd937f-7bea-4b53-9f0e-6b289152af3b/document/7c70018d-7a06-4ad6-a5bb-a1a4431a61cb/thumbnail?renditionKind=mediumview",
                     "rel":"thumbnail"
                  }
               },
which comes from the feed response. can i simply do a replace on medium with large?

**Comment by vfrancis** [comment]
yup try that
