### ISSUE TITLE
Modal animations buggy

### ISSUE THREAD

**Issue by dlipeles** [ibmcnxdev/photosharing-nodejs#60]
A recent update in Angular animations has introduced bugs into modals. This is a known issue and is being actively tracked here: angular-ui/bootstrap#3633. Seems like it is actively being worked on, maybe we can wait a few weeks for a fix. Related to issue #49

**Comment by anthonydresser** [comment]
One noted work around, revert to Angular 1.3.15, we are currently using 1.4.0.
