### ISSUE TITLE
App breaks in firefox

### ISSUE THREAD

**Issue by anthonydresser** [ibmcnxdev/photosharing-nodejs#69]
The angular does not inject correctly in firefox.
Error: [$injector:modulerr] Failed to instantiate module photoApp due to: [$injector:nomod] Module                              'photoApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.4.1/$injector/nomod?p0=photoApp minErr/<@http://localhost:3000/components/angular/angular.js:68:5 module/<@http://localhost:3000/components/angular/angular.js:1951:1 ensure@http://localhost:3000/components/angular/angular.js:1873:5 module@http://localhost:3000/components/angular/angular.js:1947:7 loadModules/<@http://localhost:3000/components/angular/angular.js:4355:11 forEach@http://localhost:3000/components/angular/angular.js:336:11 loadModules@http://localhost:3000/components/angular/angular.js:4339:5 createInjector@http://localhost:3000/components/angular/angular.js:4265:3 bootstrap/doBootstrap@http://localhost:3000/components/angular/angular.js:1621:9 bootstrap@http://localhost:3000/components/angular/angular.js:1642:5 angularInit@http://localhost:3000/components/angular/angular.js:1536:37 @http://localhost:3000/components/angular/angular.js:28289:5 trigger@http://localhost:3000/components/angular/angular.js:2989:7

**Comment by anthonydresser** [comment]
I believe the issue is angular is running before all the scripts have time to load, so some resources are available when it trys to run. I tried wrapping it in a document ready function, but it still errors, but doesn't hit the line where we initiate the module.

**Comment by dlipeles** [comment]
App functions well on Firefox now
